# Configuration for terminal menu
# menu_type options:
# - "horizontal" (default): Horizontal expanding menu
# - "cascading": Overlapping box style menu
# - "simple": Basic vertical menu
menu_type = "horizontal"

[menu_structure]
heading = "Main Menu"

[[menu_structure.menu]]
name = "Development"
[[menu_structure.menu.submenu]]
name = "Run hello.py"
command.type = "shell"
command.value = "python3 /home/backup/hello.py"

[[menu_structure.menu.submenu]]
name = "Run Tests"
command.type = "python"
command.value = "unittest discover tests"

[[menu_structure.menu]]
name = "System"
[[menu_structure.menu.submenu]]
name = "System Monitor"
command.type = "program"
command.value = "gnome-system-monitor"

[[menu_structure.menu.submenu]]
name = "Terminal"
command.type = "program"
command.value = "gnome-terminal"

[[menu_structure.menu]]
name = "Scripts"
[[menu_structure.menu.submenu]]
name = "Backup Data"
command.type = "shell"
command.value = "tar -czf backup.tar.gz /home/tn/projects"
command.working_dir = "/home/backup"

[[menu_structure.menu.submenu]]
name = "Update System"
command.type = "shell"
command.value = "sudo apt update && sudo apt upgrade -y"

[menu_colors]
# Default colors (used when specific colors are not set)
default_fg = "black"     # Default text color
default_bg = "dark gray" # Default background color

# Heading section colors
heading_fg = "light blue"      # Heading text color
heading_bg = "light gray"      # Heading background color
focus_heading_fg = "dark red"  # Focused heading text color
focus_heading_bg = "dark blue" # Focused heading background color

# Separator line colors
line_fg = "dark red"        # Line color
line_bg = "light gray"           # Line background color
focus_line_fg = "light red" # Focused line color
focus_line_bg = "dark blue" # Focused line background color

# Menu options colors
options_fg = "black"           # Menu options text color
options_bg = "light gray"      # Menu options background color
focus_options_fg = "white"     # Focused option text color
focus_options_bg = "dark blue" # Focused option background color

# Selected item colors
selected_fg = "dark red"  # Selected item text color
selected_bg = "dark blue" # Selected item background color
