[project]
name = "terminal-gui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "prompt-toolkit>=3.0.50",
    "toml>=0.10.2",
    "urwid>=2.6.16",
]
